<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>hierarchy</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hierarchy</value>
      <webElementGuid>a312833d-64d8-4125-834b-17f03d8c5691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b635b937-34b8-49f8-b4ba-5ea606abb45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>2186</value>
      <webElementGuid>29beac94-3596-4dbb-9af8-d415e8a59fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rotation</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e78e9714-056f-4f5f-a12c-a56ded6e0b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1080</value>
      <webElementGuid>80244924-3aad-470b-b1d6-865686ca82a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//hierarchy</value>
      <webElementGuid>801c424e-d9ba-4157-bfdc-b0c9ce62f895</webElementGuid>
   </webElementProperties>
   <locator>//hierarchy</locator>
   <locatorStrategy>XPATH</locatorStrategy>
</MobileElementEntity>
